#!/usr/bin/env bash

# NewTemporaryFolder.sh
# Make A New Temporary Folder (Make temporary user directory Mac)

if [ -d "~/Temporary" ]; then # If the unofficial Apple Computer Operating System user temporary folder is [exists as] a directory in the current user's home then...
	if [ -L "~/Temporary" ]; then # If the UACOSUTF is [exists as] a symbolic link in the CUH then...
		mv ~/Temporary ~/.Trash/ # Put the unof ACOS usr tmp folder symlink to the cur usr's trash, and...
		mkdir ~/Temporary # Make an UACOSUTF in the CUH.
	else # ... Else [if a UACOSUTF is a directory in the CUH] then...
		mv -R ~/Temporary ~/.Trash/ # Put the UACOSUTF to the CUT [just in case it contains documents], and...
		mkdir ~/Temporary # Make a new UACOSUTF in the CUH.
	fi
else # ... Else [if the UACOSUTF is not [does not exist]] then...
	mkdir -p ~/Temporary # Make an UACOSUTF in the CUH.
fi

# Why I did not write this the negative 'is not' (`[ ! -d "~/Temporary"`) way:
#
#  if [ ! -d "~/Temporary" ]; then # If the UACOSUTF is not [does not exist as] a directory in the current user's home then...
#    if [ -L "~/Temporary" ]; then # If the UACOSUTF is not [does not exists as] a symbolic link in the CUH then...
#      mv ~/Temporary ~/.Trash/ # Put the unof ACOS usr tmp folder symlink to the cur usr's trash, and...
#      mkdir ~/Temporary # Make an UACOSUTF in the CUH.
#    else # ... Else...
#      mkdir -p ~/Temporary # Make the UACOSUTF in the CUH.
#    fi
#  fi
#
# It would cause a sign inversion at some point to be kept clean. Checking that it doesn't exist as a symlink confronts to a weird sequence of events where one could ask '... Or else what?'.
