#!/usr/bin/env bash

if [ -d "${SYMLINK_OR_DIR}" ]; then # If $SYMLINK_OR_DIR exists then...
	if [ -L "${SYMLINK_OR_DIR}" ]; then # If $SYMLINK_OR_DIR is a symbolic link then...
		rm "${SYMLINK_OR_DIR}" # Remove $SYMLINK.
	else # Else, ie if $SYMLINK_OR_DIR is a directory, then...
		if [ $(ls -A "${SYMLINK_OR_DIR}") ]; then # If $DIR is empty then...
			mv "${SYMLINK_OR_DIR}/*" ${HOME}/Desktop/ # Move $DIR's contents to current user's desktop.
			rmdir "${SYMLINK_OR_DIR}" # Remove $DIR.
		else # Else, ie if $DIR is not empty, then...
			rmdir "${SYMLINK_OR_DIR}" # Remove $DIR.
		fi
	fi
fi

if [ ! -d "${SYMLINK_OR_DIR}" ]; then # If $SYMLINK_OR_DIR does not exist then...
	exit
fi